#!/usr/bin/env python3
"""
Anki出力をHTMLプレビュー用に変換するスクリプト
"""

def convert_anki_to_html_preview(anki_file, output_file):
    """
    AnkiのTSVファイルをHTML形式のプレビューに変換
    """
    
    html_content = """
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Anki Deck Preview</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }
        .card { 
            background: white; 
            margin: 20px 0; 
            padding: 20px; 
            border-radius: 8px; 
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            max-width: 600px;
        }
        .front { 
            font-size: 24px; 
            font-weight: bold; 
            color: #2c3e50; 
            border-bottom: 2px solid #3498db; 
            padding-bottom: 10px; 
            margin-bottom: 15px;
        }
        .back { 
            line-height: 1.6; 
            color: #333;
        }
        .card-info {
            font-size: 12px;
            color: #7f8c8d;
            margin-top: 10px;
            border-top: 1px solid #ecf0f1;
            padding-top: 10px;
        }
        .examples em {
            display: block;
            margin: 5px 0;
            padding: 5px;
            background-color: #f8f9fa;
            border-left: 3px solid #3498db;
        }
    </style>
</head>
<body>
    <h1>📚 Anki Deck Preview - TOEFL 3800 Rank3</h1>
    <p>Generated by Claude Code | <a href="https://github.com/53b29461/anki-deck-generator">GitHub Repository</a></p>
"""
    
    cards_html = ""
    card_count = 0
    
    with open(anki_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            
            # ヘッダー行をスキップ
            if line.startswith('#') or not line:
                continue
                
            parts = line.split('\t')
            if len(parts) >= 5:
                guid = parts[0]
                card_type = parts[1]
                deck_name = parts[2]
                front = parts[3]
                back = parts[4]
                tags = parts[5] if len(parts) > 5 else ""
                
                card_count += 1
                cards_html += f"""
    <div class="card">
        <div class="front">📖 {front}</div>
        <div class="back">{back}</div>
        <div class="card-info">
            <strong>GUID:</strong> {guid[:8]}... | 
            <strong>Type:</strong> {card_type} | 
            <strong>Deck:</strong> {deck_name} | 
            <strong>Tags:</strong> {tags}
        </div>
    </div>
"""
    
    html_content += cards_html
    html_content += f"""
    <div style="text-align: center; margin: 40px 0; color: #7f8c8d;">
        <p>Total Cards: <strong>{card_count}</strong></p>
        <p>Generated by Claude Code Anki Deck Generator</p>
    </div>
</body>
</html>
"""
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"HTML preview created: {output_file}")
    print(f"Total cards converted: {card_count}")

if __name__ == "__main__":
    # テスト用HTML変換
    anki_file = "../data/output/claude-code/enhanced_deck_test.txt"
    html_file = "../data/output/claude-code/preview.html"
    
    convert_anki_to_html_preview(anki_file, html_file)
    
    print("✅ HTML preview ready!")
    print("📁 Open in browser: data/output/claude-code/preview.html")
    print("🌐 Or start local server:")
    print("   cd data/output/claude-code && python3 -m http.server 8000")